apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx4
spec:
  selector:
    matchLabels:
      app: nginx4
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - name: nginx4
        image: nginx 
        ports:
        - containerPort: 80

